analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true  # Add this for stricter type checking
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"    # For mockito generated files
    - "**/generated_*.dart"

linter:
  rules:
    # Your existing rules plus...

    # Code safety
    avoid_dynamic_calls: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    depend_on_referenced_packages: true
    test_types_in_equals: true
    throw_in_finally: true
    unawaited_futures: true
    unsafe_html: true

    # Maintainability
    avoid_private_typedef_functions: true
    avoid_void_async: true
    implementation_imports: true
    no_adjacent_strings_in_list: true
    prefer_relative_imports: true
    packages_go_first: true
    
    # Style & Formatting
    indent: 2
    lines_longer_than_80_chars: true
    unnecessary_parenthesis: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_string_buffers: true
    
    # Flutter specific
    avoid_unnecessary_containers: true
    use_colored_box: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_named_constants: true
    use_super_parameters: true